name: Check

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - run: npm ci --no-audit

      - run: npm run build

      - run: npx tsd

      - run: npx eslint --report-unused-disable-directives .

      - run: npx prettier --check .
